# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glean < Formula
  desc "Enterprise search CLI for Glean"
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/JurgenLangbroek/glean-cli/releases/download/v0.1.0/glean-cli_0.1.0_darwin_all.tar.gz"
    sha256 "5b4c23882417d876ad46880846ee42f475632ee741adfbfb8647307f815e161f"

    define_method(:install) do
      bin.install "glean"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JurgenLangbroek/glean-cli/releases/download/v0.1.0/glean-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "0644851b991b965996fc3efd8eece529b4a20b3645ea11a933cd515f7ce07c78"
      define_method(:install) do
        bin.install "glean"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JurgenLangbroek/glean-cli/releases/download/v0.1.0/glean-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "027c33479c16bcf5d6eb37de78d54ee7edecdfa16430bfe4b518b001a48c286b"
      define_method(:install) do
        bin.install "glean"
      end
    end
  end

  test do
    assert_match "glean version", shell_output("#{bin}/glean version")
  end
end
