# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glean < Formula
  desc "Enterprise search CLI for Glean"
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/JurgenLangbroek/glean-cli/releases/download/v0.1.0/glean-cli_0.1.0_darwin_all.tar.gz"
    sha256 "0431f0d188d0a0de12b35f60c4823ecb265b2857199c6c74c04a7e3338162ef6"

    define_method(:install) do
      bin.install "glean"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JurgenLangbroek/glean-cli/releases/download/v0.1.0/glean-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "dd9e5930535dbaed3a7275848ca56f5a81da721b7e7c08f0e26e6847a6c59f53"
      define_method(:install) do
        bin.install "glean"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JurgenLangbroek/glean-cli/releases/download/v0.1.0/glean-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "02bcafcc574971f7af61c49a286e652249567fdcfa96dfe3054645585342ed6d"
      define_method(:install) do
        bin.install "glean"
      end
    end
  end

  test do
    assert_match "glean version", shell_output("#{bin}/glean version")
  end
end
